version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/website"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/agent"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/corpus"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/tests"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
